name: configurable
description: System Configuration and Dotenv Environment for Dart
version: 1.0.0
homepage: https://github.com/CUBETIQ/system-config-dart
repository: https://github.com/CUBETIQ/system-config-dart.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.16.8
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0
